name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        platform: [manylinux]
        arch: [x86_64, i686, aarch64, ppc64le, s390x]
        os: [ubuntu-latest]
        pyver: [cp39, cp310, cp311, cp312]
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch build
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_MANYLINUX_PPC64LE_IMAGE: manylinux2014
          CIBW_BUILD: ${{matrix.pyver}}-${{matrix.platform}}_${{matrix.arch}}
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # These archs require an Apple M1 runner: [arm64, universal2]
        arch: [x86_64]
        os: [macos-latest]
        pyver: [cp39, cp310, cp311, cp312]
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_BUILD: ${{matrix.pyver}}-macosx_${{matrix.arch}}
          CIBW_ARCHS_MACOS: x86_64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl